/**
 * Pin to Video — Cinematic Tracking System
 * Perfectly pins DOM elements to specific coordinates of an object-fit: cover video,
 * regardless of window size, aspect ratio, or cropping.
 */
(function() {
    
    // The native dimensions of your video asset (4K or 1080p standard 16:9)
    const VIDEO_WIDTH = 1920;
    const VIDEO_HEIGHT = 1080;
    const VIDEO_ASPECT = VIDEO_WIDTH / VIDEO_HEIGHT;

    // The coordinates generated by the dev tool (based on the user's specific screen)
    // The user had left: 42.63%, bottom: 69.85% on their screen.
    // We will calculate the true native video coordinates on first load,
    // and then lock them in to handle all future resizing perfectly.
    
    let nativeX = null;
    let nativeY = null;

    function calculateVideoBounds() {
        const winW = window.innerWidth;
        const winH = window.innerHeight;
        const winAspect = winW / winH;

        let vidW, vidH, offsetX, offsetY;

        if (winAspect > VIDEO_ASPECT) {
            // Window is wider than video native (Top/Bottom cropped)
            vidW = winW;
            vidH = winW / VIDEO_ASPECT;
            offsetX = 0;
            offsetY = (winH - vidH) / 2;
        } else {
            // Window is taller than video native (Left/Right cropped)
            vidW = winH * VIDEO_ASPECT;
            vidH = winH;
            offsetX = (winW - vidW) / 2;
            offsetY = 0;
        }

        return { vidW, vidH, offsetX, offsetY, winW, winH };
    }

    function initNativeCoords() {
        const icon = document.querySelector('.bottom-contact-container');
        if (!icon) return;

        // 1. Check if the dev tool has saved a custom native coordinate
        const savedX = localStorage.getItem('cherenkov_pin_x');
        const savedY = localStorage.getItem('cherenkov_pin_y');

        if (savedX !== null && savedY !== null) {
            nativeX = parseFloat(savedX);
            nativeY = parseFloat(savedY);
            return;
        }

        // 2. Fallback to hardcoded native coordinates (found via dev tool)
        // (Update these numbers when swapping to a new premium video asset)
        nativeX = 0.4276; 
        nativeY = 0.3134;
    }

    // Expose for the dev tool to call when dragging stops
    window.forcePinUpdate = function() {
        initNativeCoords();
        updatePinnedElements();
    };

    function updatePinnedElements() {
        const icon = document.querySelector('.bottom-contact-container');
        if (!icon || nativeX === null) return;

        const bounds = calculateVideoBounds();

        // Calculate exact pixel position on screen
        const screenX = bounds.offsetX + (nativeX * bounds.vidW);
        const screenY = bounds.offsetY + (nativeY * bounds.vidH);

        // Convert back to window percentages so the CSS handles it
        const leftPercent = (screenX / bounds.winW) * 100;
        const topPercent = (screenY / bounds.winH) * 100;
        const bottomPercent = 100 - topPercent;

        // Apply
        icon.style.left = `${leftPercent}%`;
        icon.style.bottom = `${bottomPercent}%`;
    }

    // Initialize and run
    window.addEventListener('load', () => {
        initNativeCoords();
        updatePinnedElements();
        
        // Listen for resizes
        window.addEventListener('resize', () => {
            requestAnimationFrame(updatePinnedElements);
        });
    });

})();
